Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.box_version = "0.0.1"

  config.vm.synced_folder "shared/", "/home/vagrant/shared"

  config.vm.provision "file", source: "", destination: ""

  config.vm.provider "virtualbox" do |v|
     v.customize ["modifyvm", :id, "--cpuexecutioncap", "80"]
     v.memory = 12288
     v.cpus = 8
  end

  config.vm.network "public_network"

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update -y
  SHELL
end
