set (CMAKE_SYSTEM_NAME Linux)
set (CMAKE_SYSTEM_PROCESSOR mips)

set (CMAKE_C_COMPILER $ENV{TOOLCHAIN_DIR}/bin/mips-openwrt-linux-gcc)
set (CMAKE_FIND_ROOT_PATH $ENV{TARGET_DIR})


set (CMAKE_STAGING_PREFIX $ENV{STAGING_DIR})

set (CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set (CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set (CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set (CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
